#!/usr/bin/env sh
# SPDX-License-Identifier: GPL-2.0-or-later
# dorun - running desktop applications inside a docker container has never been easier
# https://github.com/nggit/dorun
# Copyright (c) 2021 nggit.

# see: docker image ls
IMAGE="debian"
# IMAGE="centos"

# default command
CMD="bash"

# --------------
NORMAL="\033[0m"
RED="\033[91m"
GREEN="\033[92m"
YELLOW="\033[93m"

_HOME=$HOME/.dorun
DORUN_CONF_FILE=$_HOME/dorun.conf
XAUTHORITY=${XAUTHORITY:-$HOME/.Xauthority}

# shellcheck disable=SC1090
[ -f "$DORUN_CONF_FILE" ] && [ -r "$DORUN_CONF_FILE" ] && . "$DORUN_CONF_FILE"

containername() {
    printf "dorun_%s" "$( printf "%s" "${1%:latest}" | tr -c 0-9A-Za-z _ )"
}

docreate() {
    if [ "$( id -u )" -eq 0 ]; then
        echo "To run dorun for the first time, don't use root." 1>&2
        exit 1
    fi
    [ -e "$_HOME" ] || mkdir "$_HOME" || exit 1
    if [ ! -e "$DORUN_CONF_FILE" ]; then
        echo "IMAGE=\$IMAGE" > "$DORUN_CONF_FILE"
        echo "CMD=\$CMD" >> "$DORUN_CONF_FILE"
    fi
    XDG_CONFIG_HOME=${XDG_CONFIG_HOME:-$HOME/.config}
    XDG_DOCUMENTS_DIR=$HOME/Documents
    XDG_DOWNLOAD_DIR=$HOME/Downloads
    XDG_MUSIC_DIR=$HOME/Music
    XDG_PICTURES_DIR=$HOME/Pictures
    XDG_TEMPLATES_DIR=$HOME/Templates
    XDG_VIDEOS_DIR=$HOME/Videos
    # shellcheck disable=SC1091
    [ -f "$XDG_CONFIG_HOME/user-dirs.dirs" ] && [ -r "$XDG_CONFIG_HOME/user-dirs.dirs" ] && . "$XDG_CONFIG_HOME/user-dirs.dirs"
    printf "Creating container %s...\n" "$CONTAINER"
    docker create -it --privileged \
        --entrypoint /usr/bin/env \
        --name "$CONTAINER" \
        --network host \
        -u "$( id -u ):$( id -g )" \
        -v /dev:/dev \
        -v /tmp/.X11-unix:/tmp/.X11-unix \
        -v "$_HOME:$HOME" \
        -v "$HOME/.asoundrc:$HOME/.asoundrc" \
        -v "$XAUTHORITY:$XAUTHORITY" \
        -v "$XDG_DOCUMENTS_DIR:$XDG_DOCUMENTS_DIR" \
        -v "$XDG_DOWNLOAD_DIR:$XDG_DOWNLOAD_DIR" \
        -v "$XDG_MUSIC_DIR:$XDG_MUSIC_DIR" \
        -v "$XDG_PICTURES_DIR:$XDG_PICTURES_DIR" \
        -v "$XDG_TEMPLATES_DIR:$XDG_TEMPLATES_DIR" \
        -v "$XDG_VIDEOS_DIR:$XDG_VIDEOS_DIR" \
        "$IMAGE" sh > /dev/null 2>&1
}

doexec() {
    [ "$( id -u )" -eq 0 ] && printf "%b\n" "${YELLOW}Please be careful. You are currently using root privileges.$NORMAL"
    # shellcheck disable=SC2046
    docker exec $( [ "$IS_SHELL" -eq 1 ] && printf "%s" "-it" ) --privileged -u "$( id -u ):$( id -g )" \
        "$CONTAINER" \
        sh -c "export DISPLAY=${DISPLAY:-:0}; export HOME=$HOME; export XAUTHORITY=$XAUTHORITY; cd; \
            [ $IS_SHELL -eq 1 ] && [ -f /etc/motd ] && [ -r /etc/motd ] && cat /etc/motd; \
            if command -v ${COMMAND%% *} > /dev/null 2>&1; then $COMMAND; \
            else echo ${COMMAND%% *} not found in $CONTAINER 1>&2; sh; fi \
        "
}

dostart() {
    printf "Starting container %s...\n" "$CONTAINER"
    docker container start "$CONTAINER" > /dev/null
}

dostop() {
    printf "Stopping container %s...\n" "$CONTAINER"
    docker container stop "$CONTAINER" > /dev/null
}

doremove() {
    printf "Removing container %s...\n" "$CONTAINER"
    docker container rm "$CONTAINER" > /dev/null
}

show_help() {
    cat << EOF
dorun - https://github.com/nggit/dorun

Usage:
  dorun [OPT] [ARG...]
  ./dorun [OPT] [ARG...]

OPT:
  --image=IMAGE    this option is used to temporarily change the IMAGE variable
                   without having to edit the configuration file in $DORUN_CONF_FILE
  -i, --image      wizard mode. show the available IMAGE to choose

ARG...:
  COMMAND          example: dorun /dir/prog
                            dorun firefox
                            dorun rofi -show run
                            dorun --image=centos firefox
  -s, --stop       stopping container: $CONTAINER
  -c, --clean      removing container: $CONTAINER
  -h, --help       to see this help

Without ARG..., dorun will run the default command which is: $CMD
Make sure the program must be installed before it can be run
You can install programs by starting dorun as root
EOF
}

# -----------
case ${1-} in
    --image=*)
        [ -n "${1##*=}" ] && IMAGE=${1##*=}
        shift
        ;;
    -i|--image)
        i=0; images=
        for image in $( docker image ls --format "{{.Repository}}:{{.Tag}}:{{.ID}}" 2> /dev/null ); do
            image=${image##*<none>:}; image=${image%:*}
            images=${images:+$images,}$image
            container=$( containername "$image" )
            case $( docker container inspect --format "{{.State.Status}}" "$container" 2> /dev/null ) in
                running) containerstatus="${GREEN}running$NORMAL";;
                paused)  containerstatus="${YELLOW}paused$NORMAL";;
                exited)  containerstatus="${RED}stopped$NORMAL";;
                *)       container=; containerstatus=;;
            esac
            [ $i -eq 0 ] && printf "%-4s %-30s %-30s %s\n" "NO" "IMAGE" "CONTAINER" "STATUS"
            printf "%-4s %-30s %-30s %b\n" "$(( i += 1 ))." "$image" "$container" "$containerstatus"
        done
        if [ -n "$images" ]; then
            printf "\nPlease choose ( 1 - %s ): " "$i"
            read -r input
            if [ -n "$input" ]; then
                if test "$input" -gt 0 2> /dev/null && [ "$input" -le "$i" ]; then
                    IMAGE=$( echo "$images" | cut -d , -f "$input" )
                else
                    echo "Wrong choice." 1>&2
                    exit 1
                fi
            else
                echo "Nothing chosen." 1>&2
                exit 1
            fi
        fi
        shift
        ;;
esac

if [ $# -gt 0 ]; then
    COMMAND=$*
else
    COMMAND=$CMD
fi

CONTAINER=$( containername "$IMAGE" )

case $( basename -- "${COMMAND%% *}" ) in
    *[a-z]sh|sh)
        IS_SHELL=1
        ;;
    -s|--stop)
        dostop
        exit $?;;
    -c|--clean)
        printf "Are you sure you want to remove %s? ( 1 = Yes, Enter = No ): " "$CONTAINER"
        read -r input
        [ "$input" = 1 ] && dostop && doremove
        exit $?;;
    -h|--help)
        show_help
        exit 0;;
    *)
        IS_SHELL=0
        ;;
esac

case $( docker container inspect --format "{{.State.Status}}" "$CONTAINER" 2> /dev/null ) in
    running) doexec;;
    paused)  docker container unpause "$CONTAINER" > /dev/null && doexec;;
    exited)  dostart && doexec;;
    *)
        image=$( docker image ls --format ":{{.Repository}}:{{.Tag}}:{{.ID}}:" 2>&1 ) && \
        image=$( echo "$image" | grep ":$IMAGE:" 2> /dev/null )
        case $image in
            *$IMAGE*) docreate && dostart && doexec;;
            "")
                printf "Image %s not found.\n" "$IMAGE" 1>&2
                false;;
            *)
                printf "An error occurred: %s\n" "$image" 1>&2
                false;;
        esac
        ;;
esac

exit $?
